#NAME: Nikhil Malhotra
#EMAIL: nikhilmalhotra@g.ucla.edu
#ID: 505103892

default: dist

clean:
	-@rm -f lab4a-505103892.tar.gz

dist: clean
	tar -cvzf lab4a-505103892.tar.gz Makefile README build_run.png connected.png copy.png git.png my_beaglebone.jpg
